---

- name: Install zsh and utilities
  homebrew:
    name: '{{ item }}'
    update_homebrew: no
  with_items:
    - zsh
    - zsh-syntax-highlighting
    - zsh-autosuggestions

- name: Backup existing ~/.zshrc
  shell: if [ -f ~/.zshrc ]; then mv ~/.zshrc{,.orig}; fi

- name: Clone oh-my-zsh
  git:
    repo: git@github.com:robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh

- name: Link zshrc configuration
  file:
    src: '{{ playbook_dir }}/roles/oh-my-zsh/files/zshrc'
    dest: ~/.zshrc
    state: link

- name: Set zsh as default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true

- name: Download Solarized Dark theme
  get_url:
    url: https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Solarized%20Dark%20-%20Patched.itermcolors
    dest: /tmp/solarized_dark_patched.itermcolors

- name: Install Solarized Dark theme
  shell: open /tmp/solarized_dark_patched.itermcolors

- name: Clone powerlevel9k powerline-shell theme
  git:
    repo: git@github.com:bhilburn/powerlevel9k.git
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
