---

- name: Clone Powerline fonts
  git:
    repo: git@github.com:powerline/fonts.git
    dest: /tmp/powerline-fonts
    accept_hostkey: yes
    depth: 1
    update: yes
  become: yes

- name: Install Powerline fonts
  command: /tmp/powerline-fonts/install.sh
  become: yes


- name: Install Powerline Shell
  pip:
    name: powerline-shell
    state: latest
  become: yes

- name: Create Powerline Shell config directory
  file:
    path: ~/.config/powerline-shell
    state: directory

- name: Link Powerline Shell config
  file:
    src: '{{ playbook_dir }}/roles/powerline/files/config.json'
    dest: ~/.config/powerline-shell/config.json
    state: link
